version: "2"

run:
  timeout: 5m
  concurrency: 4
  tests: false
  modules-download-mode: readonly

linters:
  enable:
    # - errcheck
    - staticcheck
    # - revive
    - gocyclo
    # - gosec

linters-settings:
  revive:
    ignore-generated-header: true
    rules:
      - name: exported
        disabled: true
  gocyclo:
    min-complexity: 15
  gosec:
    severity: medium
    confidence: high

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/your-org/your-repo
    gofmt:
      simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
