version: "2"

run:
  timeout: 5m
  concurrency: 4
  tests: false
  modules-download-mode: readonly

linters:
  enable:
    # - errcheck
    - staticcheck
    # - revive
    - gocyclo
    # - gosec

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/your-org/your-repo
    gofmt:
      simplify: true

