package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"awesome-util/graphql/gqlgen/modules/order/ordermodel"
	"awesome-util/graphql/gqlgen/modules/user/usermodel"
	"context"
)

// ID is the resolver for the id field.
func (r *orderResolver) ID(ctx context.Context, obj *ordermodel.Order) (string, error) {
	return obj.ID.Hex(), nil
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *ordermodel.Order) (*usermodel.User, error) {
	return r.userSvc.Get(ctx, obj.UserID)
}

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

type orderResolver struct{ *Resolver }
