// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package graph

import (
	"awesome-util/graphql/gqlgen/modules/order"
	"awesome-util/graphql/gqlgen/modules/order/orderservice"
	"awesome-util/graphql/gqlgen/modules/user"
	"awesome-util/graphql/gqlgen/modules/user/userservice"
)

// Injectors from wire.go:

func New() (*Resolver, error) {
	service, err := user.New()
	if err != nil {
		return nil, err
	}
	orderserviceService, err := order.New()
	if err != nil {
		return nil, err
	}
	resolver := NewResolver(service, orderserviceService)
	return resolver, nil
}

// wire.go:

var (
	_ UserService  = (*userservice.Service)(nil)
	_ OrderService = (*orderservice.Service)(nil)
)
