// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package order

import (
	"awesome-util/graphql/gqlgen/modules/order/orderrepo"
	"awesome-util/graphql/gqlgen/modules/order/orderservice"
)

// Injectors from wire.go:

func New() (*orderservice.Service, error) {
	repository := orderrepo.New()
	service := orderservice.New(repository)
	return service, nil
}

// wire.go:

var (
	_ orderservice.Repository = (*orderrepo.Repository)(nil)
)
